"""empty message

Revision ID: 4275482b2321
Revises: c920217652ae
Create Date: 2018-02-13 10:43:17.844449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4275482b2321'
down_revision = 'c920217652ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oligos_test')
    op.add_column('oligos', sa.Column('creator_str', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oligos', 'creator_str')
    op.create_table('oligos_test',
    sa.Column('oligo_tube', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('oligo_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('date_added', sa.DATE(), nullable=True),
    sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sequence', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('restrixn_site', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('oligo_tube'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
