"""empty message

Revision ID: 7d1f99f195f9
Revises: 915d2224ed26
Create Date: 2018-02-09 17:49:05.882398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1f99f195f9'
down_revision = '915d2224ed26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oligos',
    sa.Column('oligo_tube', sa.Integer(), nullable=False),
    sa.Column('oligo_name', sa.String(length=150), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.String(length=2000), nullable=True),
    sa.Column('restrixn_site', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('oligo_tube')
    )
    op.create_index(op.f('ix_oligos_creator_id'), 'oligos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_oligos_date_added'), 'oligos', ['date_added'], unique=False)
    op.create_index(op.f('ix_oligos_oligo_name'), 'oligos', ['oligo_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oligos_oligo_name'), table_name='oligos')
    op.drop_index(op.f('ix_oligos_date_added'), table_name='oligos')
    op.drop_index(op.f('ix_oligos_creator_id'), table_name='oligos')
    op.drop_table('oligos')
    # ### end Alembic commands ###
