"""empty message

Revision ID: c920217652ae
Revises: 9e39fc2bc10e
Create Date: 2018-02-12 18:18:18.366868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c920217652ae'
down_revision = '9e39fc2bc10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'validated')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
