"""empty message

Revision ID: 0104cd460789
Revises: ec23db36936a
Create Date: 2018-04-09 09:59:02.105057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0104cd460789'
down_revision = 'ec23db36936a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plasmid', sa.Column('plasmid_type', sa.String(length=50), nullable=True))
    op.drop_column('plasmid', 'copy_no_yeast')
    op.drop_column('plasmid', 'backbone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plasmid', sa.Column('backbone', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('plasmid', sa.Column('copy_no_yeast', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('plasmid', 'plasmid_type')
    # ### end Alembic commands ###
