"""empty message

Revision ID: 04c0f2c5f46e
Revises: fffdb83cc03e
Create Date: 2018-04-17 16:03:09.420538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04c0f2c5f46e'
down_revision = 'fffdb83cc03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain_relative',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('VDY_number', sa.Integer(), nullable=True),
    sa.Column('parent_strain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['VDY_number'], ['strain.VDY_number'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.drop_column('temp_plasmid', 'parent')
    op.add_column('temp_strain', sa.Column('origin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_strain', 'origin')
    op.add_column('temp_plasmid', sa.Column('parent', mysql.VARCHAR(length=100), nullable=True))
    op.drop_table('strain_relative')
    # ### end Alembic commands ###
