"""empty message

Revision ID: 3a8a677e1ef4
Revises: cf6ab2347e17
Create Date: 2018-04-17 12:42:27.956423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8a677e1ef4'
down_revision = 'cf6ab2347e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain',
    sa.Column('VDY_number', sa.Integer(), nullable=False),
    sa.Column('other_names', sa.String(length=150), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_str', sa.String(length=50), nullable=True),
    sa.Column('strain_background', sa.String(length=50), nullable=True),
    sa.Column('notebook_ref', sa.String(length=20), nullable=True),
    sa.Column('marker', sa.String(length=50), nullable=True),
    sa.Column('plasmid', sa.String(length=100), nullable=True),
    sa.Column('plasmid_selexn', sa.String(length=50), nullable=True),
    sa.Column('validation', sa.String(length=25), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('parent', sa.String(length=10), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('VDY_number')
    )
    op.create_index(op.f('ix_strain_creator_id'), 'strain', ['creator_id'], unique=False)
    op.create_index(op.f('ix_strain_date_added'), 'strain', ['date_added'], unique=False)
    op.create_index(op.f('ix_strain_other_names'), 'strain', ['other_names'], unique=False)
    op.create_table('temp_strain',
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('other_names', sa.String(length=150), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_str', sa.String(length=50), nullable=True),
    sa.Column('strain_background', sa.String(length=50), nullable=True),
    sa.Column('notebook_ref', sa.String(length=20), nullable=True),
    sa.Column('marker', sa.String(length=50), nullable=True),
    sa.Column('plasmid', sa.String(length=100), nullable=True),
    sa.Column('plasmid_selexn', sa.String(length=50), nullable=True),
    sa.Column('validation', sa.String(length=25), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('parent', sa.String(length=10), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('temp_id')
    )
    op.create_index(op.f('ix_temp_strain_creator_id'), 'temp_strain', ['creator_id'], unique=False)
    op.create_index(op.f('ix_temp_strain_date_added'), 'temp_strain', ['date_added'], unique=False)
    op.create_index(op.f('ix_temp_strain_other_names'), 'temp_strain', ['other_names'], unique=False)
    op.create_table('strain_genotype',
    sa.Column('genotype_id', sa.Integer(), nullable=False),
    sa.Column('VDY_number', sa.Integer(), nullable=True),
    sa.Column('locus_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['VDY_number'], ['strain.VDY_number'], ),
    sa.PrimaryKeyConstraint('genotype_id')
    )
    op.create_index(op.f('ix_strain_genotype_VDY_number'), 'strain_genotype', ['VDY_number'], unique=False)
    op.create_table('temp_strain_genotype',
    sa.Column('genotype_id', sa.Integer(), nullable=False),
    sa.Column('temp_strain_id', sa.Integer(), nullable=True),
    sa.Column('locus_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['temp_strain_id'], ['temp_strain.temp_id'], ),
    sa.PrimaryKeyConstraint('genotype_id')
    )
    op.create_index(op.f('ix_temp_strain_genotype_temp_strain_id'), 'temp_strain_genotype', ['temp_strain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_strain_genotype_temp_strain_id'), table_name='temp_strain_genotype')
    op.drop_table('temp_strain_genotype')
    op.drop_index(op.f('ix_strain_genotype_VDY_number'), table_name='strain_genotype')
    op.drop_table('strain_genotype')
    op.drop_index(op.f('ix_temp_strain_other_names'), table_name='temp_strain')
    op.drop_index(op.f('ix_temp_strain_date_added'), table_name='temp_strain')
    op.drop_index(op.f('ix_temp_strain_creator_id'), table_name='temp_strain')
    op.drop_table('temp_strain')
    op.drop_index(op.f('ix_strain_other_names'), table_name='strain')
    op.drop_index(op.f('ix_strain_date_added'), table_name='strain')
    op.drop_index(op.f('ix_strain_creator_id'), table_name='strain')
    op.drop_table('strain')
    # ### end Alembic commands ###
