"""empty message

Revision ID: 79a1c00b56f8
Revises: 4275482b2321
Create Date: 2018-02-17 15:33:16.402589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79a1c00b56f8'
down_revision = '4275482b2321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_oligo',
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('oligo_tube', sa.Integer(), nullable=True),
    sa.Column('oligo_name', sa.String(length=150), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_str', sa.String(length=50), nullable=True),
    sa.Column('sequence', sa.String(length=2000), nullable=True),
    sa.Column('restrixn_site', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['oligo_tube'], ['oligos.oligo_tube'], ),
    sa.PrimaryKeyConstraint('temp_id')
    )
    op.create_index(op.f('ix_temp_oligo_creator_id'), 'temp_oligo', ['creator_id'], unique=False)
    op.create_index(op.f('ix_temp_oligo_oligo_name'), 'temp_oligo', ['oligo_name'], unique=False)
    op.create_index(op.f('ix_temp_oligo_oligo_tube'), 'temp_oligo', ['oligo_tube'], unique=False)
    op.drop_table('oligos_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oligos_test',
    sa.Column('oligo_tube', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('oligo_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('date_added', sa.DATE(), nullable=True),
    sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sequence', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('restrixn_site', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('creator_str', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oligo_tube'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_temp_oligo_oligo_tube'), table_name='temp_oligo')
    op.drop_index(op.f('ix_temp_oligo_oligo_name'), table_name='temp_oligo')
    op.drop_index(op.f('ix_temp_oligo_creator_id'), table_name='temp_oligo')
    op.drop_table('temp_oligo')
    # ### end Alembic commands ###
