"""empty message

Revision ID: cf6ab2347e17
Revises: 197c43c8b6e3
Create Date: 2018-04-10 16:40:19.576956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf6ab2347e17'
down_revision = '197c43c8b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plasmid', sa.Column('image_filename', sa.String(length=100), nullable=True))
    op.add_column('plasmid', sa.Column('map_filename', sa.String(length=100), nullable=True))
    op.drop_column('plasmid', 'has_map_file')
    op.drop_column('plasmid', 'has_image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plasmid', sa.Column('has_image_file', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('plasmid', sa.Column('has_map_file', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('plasmid', 'map_filename')
    op.drop_column('plasmid', 'image_filename')
    # ### end Alembic commands ###
