"""empty message

Revision ID: ec23db36936a
Revises: 79a1c00b56f8
Create Date: 2018-04-07 09:09:46.470502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec23db36936a'
down_revision = '79a1c00b56f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plasmid',
    sa.Column('pVD_number', sa.Integer(), nullable=False),
    sa.Column('plasmid_name', sa.String(length=150), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_str', sa.String(length=50), nullable=True),
    sa.Column('simple_description', sa.String(length=200), nullable=True),
    sa.Column('backbone', sa.String(length=100), nullable=True),
    sa.Column('vector_digest', sa.String(length=100), nullable=True),
    sa.Column('insert_digest', sa.String(length=100), nullable=True),
    sa.Column('copy_no_bacteria', sa.String(length=5), nullable=True),
    sa.Column('copy_no_yeast', sa.String(length=15), nullable=True),
    sa.Column('bac_selection', sa.String(length=25), nullable=True),
    sa.Column('yeast_mamm_selection', sa.String(length=50), nullable=True),
    sa.Column('promoter', sa.String(length=50), nullable=True),
    sa.Column('fusion', sa.String(length=50), nullable=True),
    sa.Column('sequenced', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('has_image_file', sa.Boolean(), nullable=True),
    sa.Column('has_map_file', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pVD_number')
    )
    op.create_index(op.f('ix_plasmid_creator_id'), 'plasmid', ['creator_id'], unique=False)
    op.create_index(op.f('ix_plasmid_date_added'), 'plasmid', ['date_added'], unique=False)
    op.create_index(op.f('ix_plasmid_plasmid_name'), 'plasmid', ['plasmid_name'], unique=False)
    op.create_table('plasmid_relative',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('pVD_number', sa.Integer(), nullable=True),
    sa.Column('parent_plasmid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pVD_number'], ['plasmid.pVD_number'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('temp_plasmid',
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('pVD_number', sa.Integer(), nullable=True),
    sa.Column('plasmid_name', sa.String(length=150), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_str', sa.String(length=50), nullable=True),
    sa.Column('simple_description', sa.String(length=200), nullable=True),
    sa.Column('vector_digest', sa.String(length=100), nullable=True),
    sa.Column('insert_digest', sa.String(length=100), nullable=True),
    sa.Column('copy_no_bacteria', sa.String(length=5), nullable=True),
    sa.Column('plasmid_type', sa.String(length=50), nullable=True),
    sa.Column('bac_selection', sa.String(length=25), nullable=True),
    sa.Column('yeast_mamm_selection', sa.String(length=25), nullable=True),
    sa.Column('promoter', sa.String(length=50), nullable=True),
    sa.Column('fusion', sa.String(length=50), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('map_filename', sa.String(length=100), nullable=True),
    sa.Column('sequenced', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('parent', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pVD_number'], ['plasmid.pVD_number'], ),
    sa.PrimaryKeyConstraint('temp_id')
    )
    op.create_index(op.f('ix_temp_plasmid_creator_id'), 'temp_plasmid', ['creator_id'], unique=False)
    op.create_index(op.f('ix_temp_plasmid_pVD_number'), 'temp_plasmid', ['pVD_number'], unique=False)
    op.create_index(op.f('ix_temp_plasmid_plasmid_name'), 'temp_plasmid', ['plasmid_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_plasmid_plasmid_name'), table_name='temp_plasmid')
    op.drop_index(op.f('ix_temp_plasmid_pVD_number'), table_name='temp_plasmid')
    op.drop_index(op.f('ix_temp_plasmid_creator_id'), table_name='temp_plasmid')
    op.drop_table('temp_plasmid')
    op.drop_table('plasmid_relative')
    op.drop_index(op.f('ix_plasmid_plasmid_name'), table_name='plasmid')
    op.drop_index(op.f('ix_plasmid_date_added'), table_name='plasmid')
    op.drop_index(op.f('ix_plasmid_creator_id'), table_name='plasmid')
    op.drop_table('plasmid')
    # ### end Alembic commands ###
