"""empty message

Revision ID: fffdb83cc03e
Revises: 3a8a677e1ef4
Create Date: 2018-04-17 12:45:22.165035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffdb83cc03e'
down_revision = '3a8a677e1ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strain', sa.Column('origin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strain', 'origin')
    # ### end Alembic commands ###
